### PR TITLE
Fix minor spelling and grammar errors

### PR DESCRIPTION
**Pull request by PH-KDX**
Examples include:
`seattle` -> `Seattle`
`stress filled` -> `stress-filled`
`it you want to` -> `if you want to`
`highschools` -> `high schools`

### CODE REVIEW

**Comment by Chargde-Porcupine** [comment]
Duplicate Question

**Review by Chargde-Porcupine — COMMENTED** [review]
Hydration Required

**Comment by weijuwang** [comment]
shut

**Comment by Chargde-Porcupine** [comment]
Anyways the errors already been fixed

**Comment by weijuwang** [comment]
oi matthew why you delete my comment

**Comment by PH-KDX** [comment]
> Anyways the errors already been fixed

no they haven't, go look at the website

**Comment by Chargde-Porcupine** [comment]
youre right

**Review by Chargde-Porcupine — COMMENTED** [review]
ok

**Comment by PH-KDX** [comment]
pls reopen and merge

**Comment by Chargde-Porcupine** [comment]
fine

**Comment by PH-KDX** [comment]
thx

**Pull request merged**
